### ISSUE TITLE
RTW generate executables crash

### ISSUE THREAD

**Issue by fcuzzocrea** [ShabbyX/RTAI#28]
Hi,
I'm trying to do some work with RTAILab addon for simulink, however every time that I try to execute the simulink generated executables (generated by selecting the rtai target) my PC completely hangs. This does not happen if I run the showroom C examples or by just writing by hand my C code and compiling it.
I'm writing here to know if someother (that is using simulink with RTAI) is having the same problem, and so I have to inspect the rtmain.c file, or if is something related to my configuration\hardware.
For testing I'm using RTAI 5, kernel 3.18 on arch linux, and Matlab R2014a.

Thank you, and sorry for my english.

**Comment by steffenmauch** [comment]
Have you tried the -o argument to set one-shot mode? Lat time using RTAI 4.1, it was necessary as I did something similar.

**Comment by fcuzzocrea** [comment]
Yes, I've also tried with oneshot mode but it hangs with RTAI 5 (magma).
I've talked to Paolo Mantegazza at my university and he told me that we need to watch out that question of timers that should be fixed in the rtmain.c !

**Comment by ShabbyX** [comment]
@fcuzzocrea Are you running the executable as root? If not, try it! If yes, have you tried stepping through with the debugger and trying to figure out which function causes the hang?

**Comment by fcuzzocrea** [comment]
Sorry for not replying in time ! However we have solved the issue, it was caused by the timer ! 
I've attacched the modified sched.c in my last message in the mailing list for testing, however professor Mantegazza will upload it soon on the GNA repository, so we can mark this issue as fixed ! He also uploaded the 4.1 kernel patch if you want to pull it !

**Comment by ShabbyX** [comment]
@fcuzzocrea Thanks for the update!
