### ISSUE TITLE
RTAI patch support for kernel 5.x on ubuntu 20.04

### ISSUE THREAD

**Issue by mrudulachougule** [ShabbyX/RTAI#29]
Hi, 
I am planning to upgrade our operating system and application which is being patched with RTAI on Ubuntu 14.04 (kernel 3.14) to the latest Operating System Ubuntu 20.04.

Ubuntu 20.04 supports kernel 5.x and i can see RTAI support is available up to kernel 4.19.

I'd want to be informed about any planned changes or support in the RTAI patch for kernel 5.x.

Are there any RTAI patches planned for kernel 5.x?
Is the RTAI team working on new RTAI fixes for the 5.x kernel?
If so, when will the RTAI fixes for kernel version 5.x be available?

It would be beneficial to plan and work in accordance with the above information.

Anyone has any idea about RTAI patch for kernel 5.x. Please do share your feedback/ views ASAP.

Thank you for your excellent assistance.

Thanks,
Mrudula

**Comment by ShabbyX** [comment]
Hi,

I no longer maintain this repository, and haven't worked with RTAI for numerous years. The RTAI home page is at https://www.rtai.org/ and you can join the mailing list for discussions and questions like that: https://www.rtai.org/?Subscribe%2FUnsubscribe

Based on the latest RTAI release, I see that Linux 4.19 is the latest they support.

**Comment by NTULINUX** [comment]
RTAI doesn't work on 5.X kernels yet, the FPU changes in kernel 5.2 has completely broken RTAI for now. Paolo tried sorting it out but with no luck so far.
