### ISSUE TITLE
rtai_serial module not working with rtai -5.3 

### ISSUE THREAD

**Issue by mrudulachougule** [ShabbyX/RTAI#30]
Hi Shahbaz
Hope you are doing well.
Brief on our setup:
we have recently migrated ubuntu os from 14.04 to ubuntu 20.04 and hence we also ported rtai - 5.3 from rtai 4.1.
rtai_serial driver was running fine on ubuntu 14.04 platform. rtai_serial module is not working on ubuntu 20.04. To debug in detail i have added a few debug prints and seems like it is getting stuck with the RTE_TIMEOUT error on rtai_semaphore.

I have used the below parameters for serial configuration and task periodicity is one sec. The application is stuck while reading data over rtai serial module.

modbus_new_rtai(0, 9600, RT_SP_PARITY_NONE, 8, 1, RT_SP_NO_HAND_SHAKE,
                                   RT_SP_FIFO_SIZE_4, nano2count(one_tenth_sec));

Please share your views on the above problem.

Appreciate your help!

**Comment by NTULINUX** [comment]
This tree on Github has been abandoned for a long while now.

Please send an email to the official RTAI mailing list at rtai@rtai.org
